limit_req_zone $binary_remote_addr zone=kontur_api:10m rate=30r/s;
limit_req_zone $binary_remote_addr zone=kontur_webhook:10m rate=2r/s;
limit_req_zone $binary_remote_addr zone=kontur_admin:10m rate=30r/s;
limit_conn_zone $binary_remote_addr zone=kontur_connections:10m;
